//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeTracker.App.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TimeTracker.App.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desconocida.
        /// </summary>
        public static string Activity_Unknown {
            get {
                return ResourceManager.GetString("Activity_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Añadir entrada.
        /// </summary>
        public static string Button_AddRecord {
            get {
                return ResourceManager.GetString("Button_AddRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Añadir franja.
        /// </summary>
        public static string Button_AddSlot {
            get {
                return ResourceManager.GetString("Button_AddSlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string Button_CancelDelete {
            get {
                return ResourceManager.GetString("Button_CancelDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear actividad.
        /// </summary>
        public static string Button_CreateActivity {
            get {
                return ResourceManager.GetString("Button_CreateActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar.
        /// </summary>
        public static string Button_Delete {
            get {
                return ResourceManager.GetString("Button_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nueva actividad.
        /// </summary>
        public static string Button_NewActivity {
            get {
                return ResourceManager.GetString("Button_NewActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nueva entrada.
        /// </summary>
        public static string Button_NewRecord {
            get {
                return ResourceManager.GetString("Button_NewRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        public static string Button_Save {
            get {
                return ResourceManager.GetString("Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar cambios.
        /// </summary>
        public static string Button_SaveChanges {
            get {
                return ResourceManager.GetString("Button_SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoy.
        /// </summary>
        public static string Button_Today {
            get {
                return ResourceManager.GetString("Button_Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actividad activa.
        /// </summary>
        public static string CheckBox_ActivityActive {
            get {
                return ResourceManager.GetString("CheckBox_ActivityActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecciona el idioma de la interfaz.
        /// </summary>
        public static string Description_Language {
            get {
                return ResourceManager.GetString("Description_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muestra notificaciones para recordarte registrar las horas.
        /// </summary>
        public static string Description_Notifications {
            get {
                return ResourceManager.GetString("Description_Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define la duración esperada de tu jornada laboral diaria.
        /// </summary>
        public static string Description_WorkdayDuration {
            get {
                return ResourceManager.GetString("Description_WorkdayDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Eliminar actividad?.
        /// </summary>
        public static string Dialog_DeleteActivity_Title {
            get {
                return ResourceManager.GetString("Dialog_DeleteActivity_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar actividad.
        /// </summary>
        public static string Dialog_EditActivity_Title {
            get {
                return ResourceManager.GetString("Dialog_EditActivity_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar entrada.
        /// </summary>
        public static string Dialog_EditRecord_Title {
            get {
                return ResourceManager.GetString("Dialog_EditRecord_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar franja.
        /// </summary>
        public static string Dialog_EditSlot_Title {
            get {
                return ResourceManager.GetString("Dialog_EditSlot_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nueva actividad.
        /// </summary>
        public static string Dialog_NewActivity_Title {
            get {
                return ResourceManager.GetString("Dialog_NewActivity_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Añadir nueva entrada.
        /// </summary>
        public static string Dialog_NewRecord_Title {
            get {
                return ResourceManager.GetString("Dialog_NewRecord_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Añadir franja.
        /// </summary>
        public static string Dialog_NewSlot_Title {
            get {
                return ResourceManager.GetString("Dialog_NewSlot_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Añade tu primera franja horaria.
        /// </summary>
        public static string Empty_AddFirstSlot {
            get {
                return ResourceManager.GetString("Empty_AddFirstSlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crea tu primera actividad.
        /// </summary>
        public static string Empty_CreateFirstActivity {
            get {
                return ResourceManager.GetString("Empty_CreateFirstActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crea tu primer registro de tiempo.
        /// </summary>
        public static string Empty_CreateFirstRecord {
            get {
                return ResourceManager.GetString("Empty_CreateFirstRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hay actividades.
        /// </summary>
        public static string Empty_NoActivities {
            get {
                return ResourceManager.GetString("Empty_NoActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hay registros.
        /// </summary>
        public static string Empty_NoRecords {
            get {
                return ResourceManager.GetString("Empty_NoRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hay franjas para este día.
        /// </summary>
        public static string Empty_NoSlots {
            get {
                return ResourceManager.GetString("Empty_NoSlots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todas las actividades.
        /// </summary>
        public static string Filter_AllActivities {
            get {
                return ResourceManager.GetString("Filter_AllActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}h {1}m.
        /// </summary>
        public static string Format_Duration {
            get {
                return ResourceManager.GetString("Format_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actividad.
        /// </summary>
        public static string Label_Activity {
            get {
                return ResourceManager.GetString("Label_Activity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de la actividad.
        /// </summary>
        public static string Label_ActivityName {
            get {
                return ResourceManager.GetString("Label_ActivityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idioma de la aplicación.
        /// </summary>
        public static string Label_AppLanguage {
            get {
                return ResourceManager.GetString("Label_AppLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplicación:.
        /// </summary>
        public static string Label_Application {
            get {
                return ResourceManager.GetString("Label_Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tema de la aplicación.
        /// </summary>
        public static string Label_AppTheme {
            get {
                return ResourceManager.GetString("Label_AppTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string Label_Color {
            get {
                return ResourceManager.GetString("Label_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha.
        /// </summary>
        public static string Label_Date {
            get {
                return ResourceManager.GetString("Label_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        public static string Label_DateDisplay {
            get {
                return ResourceManager.GetString("Label_DateDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activar notificaciones.
        /// </summary>
        public static string Label_EnableNotifications {
            get {
                return ResourceManager.GetString("Label_EnableNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hora fin.
        /// </summary>
        public static string Label_EndTime {
            get {
                return ResourceManager.GetString("Label_EndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        public static string Label_Location {
            get {
                return ResourceManager.GetString("Label_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notas (opcional).
        /// </summary>
        public static string Label_Notes {
            get {
                return ResourceManager.GetString("Label_Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oficina.
        /// </summary>
        public static string Label_OfficeBar {
            get {
                return ResourceManager.GetString("Label_OfficeBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        public static string Label_SelectedDay {
            get {
                return ResourceManager.GetString("Label_SelectedDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hora inicio.
        /// </summary>
        public static string Label_StartTime {
            get {
                return ResourceManager.GetString("Label_StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tecnología:.
        /// </summary>
        public static string Label_Technology {
            get {
                return ResourceManager.GetString("Label_Technology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teletrabajo.
        /// </summary>
        public static string Label_TeleworkBar {
            get {
                return ResourceManager.GetString("Label_TeleworkBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % Teletrabajo.
        /// </summary>
        public static string Label_TeleworkPercentage {
            get {
                return ResourceManager.GetString("Label_TeleworkPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiempo total.
        /// </summary>
        public static string Label_TotalTime {
            get {
                return ResourceManager.GetString("Label_TotalTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total trabajado.
        /// </summary>
        public static string Label_TotalWorked {
            get {
                return ResourceManager.GetString("Label_TotalWorked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        public static string Label_TotalWorkedDay {
            get {
                return ResourceManager.GetString("Label_TotalWorkedDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versión:.
        /// </summary>
        public static string Label_Version {
            get {
                return ResourceManager.GetString("Label_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiempo total de la jornada.
        /// </summary>
        public static string Label_WorkdayDuration {
            get {
                return ResourceManager.GetString("Label_WorkdayDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lugar de trabajo.
        /// </summary>
        public static string Label_WorkLocation {
            get {
                return ResourceManager.GetString("Label_WorkLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oficina.
        /// </summary>
        public static string Location_Office {
            get {
                return ResourceManager.GetString("Location_Office", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Casa (teletrabajo).
        /// </summary>
        public static string Location_Telework {
            get {
                return ResourceManager.GetString("Location_Telework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar.
        /// </summary>
        public static string Menu_Delete {
            get {
                return ResourceManager.GetString("Menu_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string Menu_Edit {
            get {
                return ResourceManager.GetString("Menu_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esta actividad tiene {0} registros asociados. Si la eliminas, se perderán todos los datos..
        /// </summary>
        public static string Message_DeleteActivityWarning {
            get {
                return ResourceManager.GetString("Message_DeleteActivityWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actividades.
        /// </summary>
        public static string Nav_Activities {
            get {
                return ResourceManager.GetString("Nav_Activities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registros.
        /// </summary>
        public static string Nav_Records {
            get {
                return ResourceManager.GetString("Nav_Records", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opciones.
        /// </summary>
        public static string Nav_Settings {
            get {
                return ResourceManager.GetString("Nav_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jornada.
        /// </summary>
        public static string Nav_Workday {
            get {
                return ResourceManager.GetString("Nav_Workday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestiona tus actividades y tareas.
        /// </summary>
        public static string Page_Activities_Subtitle {
            get {
                return ResourceManager.GetString("Page_Activities_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actividades.
        /// </summary>
        public static string Page_Activities_Title {
            get {
                return ResourceManager.GetString("Page_Activities_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registros de tiempo.
        /// </summary>
        public static string Page_Records_Title {
            get {
                return ResourceManager.GetString("Page_Records_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuración de la aplicación.
        /// </summary>
        public static string Page_Settings_Subtitle {
            get {
                return ResourceManager.GetString("Page_Settings_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opciones.
        /// </summary>
        public static string Page_Settings_Title {
            get {
                return ResourceManager.GetString("Page_Settings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control de tu jornada de trabajo.
        /// </summary>
        public static string Page_Workday_Subtitle {
            get {
                return ResourceManager.GetString("Page_Workday_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jornada laboral.
        /// </summary>
        public static string Page_Workday_Title {
            get {
                return ResourceManager.GetString("Page_Workday_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de la actividad....
        /// </summary>
        public static string Placeholder_ActivityName {
            get {
                return ResourceManager.GetString("Placeholder_ActivityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todas las actividades.
        /// </summary>
        public static string Placeholder_AllActivities {
            get {
                return ResourceManager.GetString("Placeholder_AllActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Añade notas sobre esta entrada....
        /// </summary>
        public static string Placeholder_RecordNotes {
            get {
                return ResourceManager.GetString("Placeholder_RecordNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar por actividad o notas....
        /// </summary>
        public static string Placeholder_Search {
            get {
                return ResourceManager.GetString("Placeholder_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecciona una actividad.
        /// </summary>
        public static string Placeholder_SelectActivity {
            get {
                return ResourceManager.GetString("Placeholder_SelectActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HH:mm.
        /// </summary>
        public static string Placeholder_Time {
            get {
                return ResourceManager.GetString("Placeholder_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Català.
        /// </summary>
        public static string RadioButton_Catalan {
            get {
                return ResourceManager.GetString("RadioButton_Catalan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oscuro.
        /// </summary>
        public static string RadioButton_DarkTheme {
            get {
                return ResourceManager.GetString("RadioButton_DarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claro.
        /// </summary>
        public static string RadioButton_LightTheme {
            get {
                return ResourceManager.GetString("RadioButton_LightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oficina.
        /// </summary>
        public static string RadioButton_Office {
            get {
                return ResourceManager.GetString("RadioButton_Office", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Español.
        /// </summary>
        public static string RadioButton_Spanish {
            get {
                return ResourceManager.GetString("RadioButton_Spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sistema.
        /// </summary>
        public static string RadioButton_SystemLanguage {
            get {
                return ResourceManager.GetString("RadioButton_SystemLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sistema.
        /// </summary>
        public static string RadioButton_SystemTheme {
            get {
                return ResourceManager.GetString("RadioButton_SystemTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Casa (teletrabajo).
        /// </summary>
        public static string RadioButton_Telework {
            get {
                return ResourceManager.GetString("RadioButton_Telework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sobre la aplicación.
        /// </summary>
        public static string Section_About {
            get {
                return ResourceManager.GetString("Section_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apariencia.
        /// </summary>
        public static string Section_Appearance {
            get {
                return ResourceManager.GetString("Section_Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idioma.
        /// </summary>
        public static string Section_Language {
            get {
                return ResourceManager.GetString("Section_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resumen mensual.
        /// </summary>
        public static string Section_MonthlySummary {
            get {
                return ResourceManager.GetString("Section_MonthlySummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notificaciones.
        /// </summary>
        public static string Section_Notifications {
            get {
                return ResourceManager.GetString("Section_Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Franjas horarias.
        /// </summary>
        public static string Section_TimeSlots {
            get {
                return ResourceManager.GetString("Section_TimeSlots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jornada laboral.
        /// </summary>
        public static string Section_WorkdaySettings {
            get {
                return ResourceManager.GetString("Section_WorkdaySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} entradas.
        /// </summary>
        public static string Stat_Entries {
            get {
                return ResourceManager.GetString("Stat_Entries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oficina.
        /// </summary>
        public static string Stat_Office {
            get {
                return ResourceManager.GetString("Stat_Office", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teletrabajo.
        /// </summary>
        public static string Stat_Telework {
            get {
                return ResourceManager.GetString("Stat_Telework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % Teletrabajo.
        /// </summary>
        public static string Stat_TeleworkPercentage {
            get {
                return ResourceManager.GetString("Stat_TeleworkPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoy has trabajado {0}.
        /// </summary>
        public static string Stat_TodayWorked {
            get {
                return ResourceManager.GetString("Stat_TodayWorked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Stat_Total {
            get {
                return ResourceManager.GetString("Stat_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activa.
        /// </summary>
        public static string Status_Active {
            get {
                return ResourceManager.GetString("Status_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactiva.
        /// </summary>
        public static string Status_Inactive {
            get {
                return ResourceManager.GetString("Status_Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control de tiempo.
        /// </summary>
        public static string TitleBar_Subtitle {
            get {
                return ResourceManager.GetString("TitleBar_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TimeTracker.
        /// </summary>
        public static string TitleBar_Title {
            get {
                return ResourceManager.GetString("TitleBar_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to horas.
        /// </summary>
        public static string Unit_Hours {
            get {
                return ResourceManager.GetString("Unit_Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutos.
        /// </summary>
        public static string Unit_Minutes {
            get {
                return ResourceManager.GetString("Unit_Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La hora de fin debe ser posterior a la hora de inicio..
        /// </summary>
        public static string Validation_EndTimeAfterStartTime {
            get {
                return ResourceManager.GetString("Validation_EndTimeAfterStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La hora de fin no es válida..
        /// </summary>
        public static string Validation_InvalidEndTime {
            get {
                return ResourceManager.GetString("Validation_InvalidEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La hora de inicio no es válida..
        /// </summary>
        public static string Validation_InvalidStartTime {
            get {
                return ResourceManager.GetString("Validation_InvalidStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El registro se solapa con otro registro existente ({0} - {1})..
        /// </summary>
        public static string Validation_OverlappingRecord {
            get {
                return ResourceManager.GetString("Validation_OverlappingRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La franja se solapa con otra franja existente ({0} - {1})..
        /// </summary>
        public static string Validation_OverlappingSlot {
            get {
                return ResourceManager.GetString("Validation_OverlappingSlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TimeTracker.
        /// </summary>
        public static string Value_AppName {
            get {
                return ResourceManager.GetString("Value_AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET 10, WPF, SQLite.
        /// </summary>
        public static string Value_Technology {
            get {
                return ResourceManager.GetString("Value_Technology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TimeTracker.
        /// </summary>
        public static string Window_Title {
            get {
                return ResourceManager.GetString("Window_Title", resourceCulture);
            }
        }
    }
}
