//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeTracker.App.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TimeTracker.App.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:n0} registros · {1}.
        /// </summary>
        internal static string Activities_Subtitle {
            get {
                return ResourceManager.GetString("Activities_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:n0} registros.
        /// </summary>
        internal static string Activity_MultipleRecords {
            get {
                return ResourceManager.GetString("Activity_MultipleRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sin registros.
        /// </summary>
        internal static string Activity_NoRecords {
            get {
                return ResourceManager.GetString("Activity_NoRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 registro.
        /// </summary>
        internal static string Activity_SingleRecord {
            get {
                return ResourceManager.GetString("Activity_SingleRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desconocida.
        /// </summary>
        internal static string Activity_Unknown {
            get {
                return ResourceManager.GetString("Activity_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esta actividad tiene {0} registros asociados. Si la eliminas, se perderán todos los datos..
        /// </summary>
        internal static string ActivityDetail_DeleteWarning {
            get {
                return ResourceManager.GetString("ActivityDetail_DeleteWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nueva actividad.
        /// </summary>
        internal static string ActivityDetail_NewTitle {
            get {
                return ResourceManager.GetString("ActivityDetail_NewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registros.
        /// </summary>
        internal static string ActivityDetail_RecordCount {
            get {
                return ResourceManager.GetString("ActivityDetail_RecordCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estadísticas.
        /// </summary>
        internal static string ActivityDetail_Statistics {
            get {
                return ResourceManager.GetString("ActivityDetail_Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yatta.
        /// </summary>
        internal static string App_Title {
            get {
                return ResourceManager.GetString("App_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Añadir entrada.
        /// </summary>
        internal static string Button_AddRecord {
            get {
                return ResourceManager.GetString("Button_AddRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Añadir franja.
        /// </summary>
        internal static string Button_AddSlot {
            get {
                return ResourceManager.GetString("Button_AddSlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archivar.
        /// </summary>
        internal static string Button_Archive {
            get {
                return ResourceManager.GetString("Button_Archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atrás.
        /// </summary>
        internal static string Button_Back {
            get {
                return ResourceManager.GetString("Button_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        internal static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        internal static string Button_CancelDelete {
            get {
                return ResourceManager.GetString("Button_CancelDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear actividad.
        /// </summary>
        internal static string Button_CreateActivity {
            get {
                return ResourceManager.GetString("Button_CreateActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar.
        /// </summary>
        internal static string Button_Delete {
            get {
                return ResourceManager.GetString("Button_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nueva actividad.
        /// </summary>
        internal static string Button_NewActivity {
            get {
                return ResourceManager.GetString("Button_NewActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nueva entrada.
        /// </summary>
        internal static string Button_NewRecord {
            get {
                return ResourceManager.GetString("Button_NewRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        internal static string Button_Save {
            get {
                return ResourceManager.GetString("Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar cambios.
        /// </summary>
        internal static string Button_SaveChanges {
            get {
                return ResourceManager.GetString("Button_SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoy.
        /// </summary>
        internal static string Button_Today {
            get {
                return ResourceManager.GetString("Button_Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desarchivar.
        /// </summary>
        internal static string Button_Unarchive {
            get {
                return ResourceManager.GetString("Button_Unarchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actividad activa.
        /// </summary>
        internal static string CheckBox_ActivityActive {
            get {
                return ResourceManager.GetString("CheckBox_ActivityActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecciona el idioma de la interfaz.
        /// </summary>
        internal static string Description_Language {
            get {
                return ResourceManager.GetString("Description_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecciona el idioma de la aplicación. Esto invalidará el idioma predeterminado del sistema..
        /// </summary>
        internal static string Description_LanguageRequiresRestart {
            get {
                return ResourceManager.GetString("Description_LanguageRequiresRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Al cerrar la ventana, minimiza la aplicación a la bandeja en lugar de salir.
        /// </summary>
        internal static string Description_MinimizeToTray {
            get {
                return ResourceManager.GetString("Description_MinimizeToTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiempo en minutos entre cada notificación (mínimo 15, máximo 480).
        /// </summary>
        internal static string Description_NotificationInterval {
            get {
                return ResourceManager.GetString("Description_NotificationInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muestra notificaciones para recordarte registrar las horas.
        /// </summary>
        internal static string Description_Notifications {
            get {
                return ResourceManager.GetString("Description_Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define la duración esperada de tu jornada laboral diaria.
        /// </summary>
        internal static string Description_WorkdayDuration {
            get {
                return ResourceManager.GetString("Description_WorkdayDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Eliminar actividad?.
        /// </summary>
        internal static string Dialog_DeleteActivity_Title {
            get {
                return ResourceManager.GetString("Dialog_DeleteActivity_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Estás seguro de que quieres eliminar este registro? Esta acción no se puede deshacer..
        /// </summary>
        internal static string Dialog_DeleteRecord_Message {
            get {
                return ResourceManager.GetString("Dialog_DeleteRecord_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Eliminar registro?.
        /// </summary>
        internal static string Dialog_DeleteRecord_Title {
            get {
                return ResourceManager.GetString("Dialog_DeleteRecord_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar actividad.
        /// </summary>
        internal static string Dialog_EditActivity_Title {
            get {
                return ResourceManager.GetString("Dialog_EditActivity_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar entrada.
        /// </summary>
        internal static string Dialog_EditRecord_Title {
            get {
                return ResourceManager.GetString("Dialog_EditRecord_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar franja.
        /// </summary>
        internal static string Dialog_EditSlot_Title {
            get {
                return ResourceManager.GetString("Dialog_EditSlot_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nueva actividad.
        /// </summary>
        internal static string Dialog_NewActivity_Title {
            get {
                return ResourceManager.GetString("Dialog_NewActivity_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Añadir nueva entrada.
        /// </summary>
        internal static string Dialog_NewRecord_Title {
            get {
                return ResourceManager.GetString("Dialog_NewRecord_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Añadir franja.
        /// </summary>
        internal static string Dialog_NewSlot_Title {
            get {
                return ResourceManager.GetString("Dialog_NewSlot_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Añade tu primera franja horaria.
        /// </summary>
        internal static string Empty_AddFirstSlot {
            get {
                return ResourceManager.GetString("Empty_AddFirstSlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crea tu primera actividad.
        /// </summary>
        internal static string Empty_CreateFirstActivity {
            get {
                return ResourceManager.GetString("Empty_CreateFirstActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crea tu primer registro de tiempo.
        /// </summary>
        internal static string Empty_CreateFirstRecord {
            get {
                return ResourceManager.GetString("Empty_CreateFirstRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hay actividades.
        /// </summary>
        internal static string Empty_NoActivities {
            get {
                return ResourceManager.GetString("Empty_NoActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hay registros.
        /// </summary>
        internal static string Empty_NoRecords {
            get {
                return ResourceManager.GetString("Empty_NoRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hay franjas para este día.
        /// </summary>
        internal static string Empty_NoSlots {
            get {
                return ResourceManager.GetString("Empty_NoSlots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todas las actividades.
        /// </summary>
        internal static string Filter_AllActivities {
            get {
                return ResourceManager.GetString("Filter_AllActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar por actividad o notas....
        /// </summary>
        internal static string Filter_SearchByActivityOrNotes {
            get {
                return ResourceManager.GetString("Filter_SearchByActivityOrNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar por nombre....
        /// </summary>
        internal static string Filter_SearchByName {
            get {
                return ResourceManager.GetString("Filter_SearchByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mostrar archivadas.
        /// </summary>
        internal static string Filter_ShowArchived {
            get {
                return ResourceManager.GetString("Filter_ShowArchived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mostrar inactivas.
        /// </summary>
        internal static string Filter_ShowInactive {
            get {
                return ResourceManager.GetString("Filter_ShowInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}h {1}m.
        /// </summary>
        internal static string Format_Duration {
            get {
                return ResourceManager.GetString("Format_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actividad.
        /// </summary>
        internal static string Label_Activity {
            get {
                return ResourceManager.GetString("Label_Activity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de la actividad.
        /// </summary>
        internal static string Label_ActivityName {
            get {
                return ResourceManager.GetString("Label_ActivityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idioma de la aplicación.
        /// </summary>
        internal static string Label_AppLanguage {
            get {
                return ResourceManager.GetString("Label_AppLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplicación:.
        /// </summary>
        internal static string Label_Application {
            get {
                return ResourceManager.GetString("Label_Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tema de la aplicación.
        /// </summary>
        internal static string Label_AppTheme {
            get {
                return ResourceManager.GetString("Label_AppTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        internal static string Label_Color {
            get {
                return ResourceManager.GetString("Label_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha.
        /// </summary>
        internal static string Label_Date {
            get {
                return ResourceManager.GetString("Label_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        internal static string Label_DateDisplay {
            get {
                return ResourceManager.GetString("Label_DateDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activar notificaciones.
        /// </summary>
        internal static string Label_EnableNotifications {
            get {
                return ResourceManager.GetString("Label_EnableNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hora fin.
        /// </summary>
        internal static string Label_EndTime {
            get {
                return ResourceManager.GetString("Label_EndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idioma (requiere reiniciar).
        /// </summary>
        internal static string Label_LanguageRequiresRestart {
            get {
                return ResourceManager.GetString("Label_LanguageRequiresRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        internal static string Label_Location {
            get {
                return ResourceManager.GetString("Label_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimizar a la bandeja del sistema.
        /// </summary>
        internal static string Label_MinimizeToTray {
            get {
                return ResourceManager.GetString("Label_MinimizeToTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutos.
        /// </summary>
        internal static string Label_Minutes {
            get {
                return ResourceManager.GetString("Label_Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notas (opcional).
        /// </summary>
        internal static string Label_Notes {
            get {
                return ResourceManager.GetString("Label_Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intervalo de notificaciones.
        /// </summary>
        internal static string Label_NotificationInterval {
            get {
                return ResourceManager.GetString("Label_NotificationInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oficina.
        /// </summary>
        internal static string Label_OfficeBar {
            get {
                return ResourceManager.GetString("Label_OfficeBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        internal static string Label_SelectedDay {
            get {
                return ResourceManager.GetString("Label_SelectedDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hora inicio.
        /// </summary>
        internal static string Label_StartTime {
            get {
                return ResourceManager.GetString("Label_StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tecnología:.
        /// </summary>
        internal static string Label_Technology {
            get {
                return ResourceManager.GetString("Label_Technology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teletrabajo.
        /// </summary>
        internal static string Label_TeleworkBar {
            get {
                return ResourceManager.GetString("Label_TeleworkBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % Teletrabajo.
        /// </summary>
        internal static string Label_TeleworkPercentage {
            get {
                return ResourceManager.GetString("Label_TeleworkPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecciona el tema de la interfaz de usuario.
        /// </summary>
        internal static string Label_ThemeDescription {
            get {
                return ResourceManager.GetString("Label_ThemeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiempo total.
        /// </summary>
        internal static string Label_TotalTime {
            get {
                return ResourceManager.GetString("Label_TotalTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total trabajado.
        /// </summary>
        internal static string Label_TotalWorked {
            get {
                return ResourceManager.GetString("Label_TotalWorked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        internal static string Label_TotalWorkedDay {
            get {
                return ResourceManager.GetString("Label_TotalWorkedDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versión:.
        /// </summary>
        internal static string Label_Version {
            get {
                return ResourceManager.GetString("Label_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiempo total de la jornada.
        /// </summary>
        internal static string Label_WorkdayDuration {
            get {
                return ResourceManager.GetString("Label_WorkdayDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lugar de trabajo.
        /// </summary>
        internal static string Label_WorkLocation {
            get {
                return ResourceManager.GetString("Label_WorkLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oficina.
        /// </summary>
        internal static string Location_Office {
            get {
                return ResourceManager.GetString("Location_Office", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Casa (teletrabajo).
        /// </summary>
        internal static string Location_Telework {
            get {
                return ResourceManager.GetString("Location_Telework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar.
        /// </summary>
        internal static string Menu_Delete {
            get {
                return ResourceManager.GetString("Menu_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        internal static string Menu_Edit {
            get {
                return ResourceManager.GetString("Menu_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esta actividad tiene {0} registros asociados. Si la eliminas, se perderán todos los datos..
        /// </summary>
        internal static string Message_DeleteActivityWarning {
            get {
                return ResourceManager.GetString("Message_DeleteActivityWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actividades.
        /// </summary>
        internal static string Nav_Activities {
            get {
                return ResourceManager.GetString("Nav_Activities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registros.
        /// </summary>
        internal static string Nav_Records {
            get {
                return ResourceManager.GetString("Nav_Records", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opciones.
        /// </summary>
        internal static string Nav_Settings {
            get {
                return ResourceManager.GetString("Nav_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jornada.
        /// </summary>
        internal static string Nav_Workday {
            get {
                return ResourceManager.GetString("Nav_Workday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novedades.
        /// </summary>
        internal static string Nav_WhatsNew {
            get {
                return ResourceManager.GetString("Nav_WhatsNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15 minutos.
        /// </summary>
        internal static string Notification_15min {
            get {
                return ResourceManager.GetString("Notification_15min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 hora.
        /// </summary>
        internal static string Notification_1hour {
            get {
                return ResourceManager.GetString("Notification_1hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 horas.
        /// </summary>
        internal static string Notification_2hours {
            get {
                return ResourceManager.GetString("Notification_2hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 minutos.
        /// </summary>
        internal static string Notification_30min {
            get {
                return ResourceManager.GetString("Notification_30min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambiar actividad.
        /// </summary>
        internal static string Notification_ChangeActivity {
            get {
                return ResourceManager.GetString("Notification_ChangeActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuar.
        /// </summary>
        internal static string Notification_Continue {
            get {
                return ResourceManager.GetString("Notification_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiempo transcurrido: {0}.
        /// </summary>
        internal static string Notification_Duration {
            get {
                return ResourceManager.GetString("Notification_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posponer.
        /// </summary>
        internal static string Notification_Snooze {
            get {
                return ResourceManager.GetString("Notification_Snooze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Sigues trabajando en: {0}?.
        /// </summary>
        internal static string Notification_StillWorking {
            get {
                return ResourceManager.GetString("Notification_StillWorking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actividad desconocida.
        /// </summary>
        internal static string Notification_UnknownActivity {
            get {
                return ResourceManager.GetString("Notification_UnknownActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestiona tus actividades y tareas.
        /// </summary>
        internal static string Page_Activities_Subtitle {
            get {
                return ResourceManager.GetString("Page_Activities_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actividades.
        /// </summary>
        internal static string Page_Activities_Title {
            get {
                return ResourceManager.GetString("Page_Activities_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registros de tiempo.
        /// </summary>
        internal static string Page_Records_Title {
            get {
                return ResourceManager.GetString("Page_Records_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuración de la aplicación.
        /// </summary>
        internal static string Page_Settings_Subtitle {
            get {
                return ResourceManager.GetString("Page_Settings_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opciones.
        /// </summary>
        internal static string Page_Settings_Title {
            get {
                return ResourceManager.GetString("Page_Settings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novedades.
        /// </summary>
        internal static string Page_WhatsNew_Title {
            get {
                return ResourceManager.GetString("Page_WhatsNew_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control de tu jornada de trabajo.
        /// </summary>
        internal static string Page_Workday_Subtitle {
            get {
                return ResourceManager.GetString("Page_Workday_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jornada laboral.
        /// </summary>
        internal static string Page_Workday_Title {
            get {
                return ResourceManager.GetString("Page_Workday_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de la actividad....
        /// </summary>
        internal static string Placeholder_ActivityName {
            get {
                return ResourceManager.GetString("Placeholder_ActivityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todas las actividades.
        /// </summary>
        internal static string Placeholder_AllActivities {
            get {
                return ResourceManager.GetString("Placeholder_AllActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Añade notas sobre esta entrada....
        /// </summary>
        internal static string Placeholder_RecordNotes {
            get {
                return ResourceManager.GetString("Placeholder_RecordNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar por actividad o notas....
        /// </summary>
        internal static string Placeholder_Search {
            get {
                return ResourceManager.GetString("Placeholder_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecciona una actividad.
        /// </summary>
        internal static string Placeholder_SelectActivity {
            get {
                return ResourceManager.GetString("Placeholder_SelectActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HH:mm.
        /// </summary>
        internal static string Placeholder_Time {
            get {
                return ResourceManager.GetString("Placeholder_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Català.
        /// </summary>
        internal static string RadioButton_Catalan {
            get {
                return ResourceManager.GetString("RadioButton_Catalan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oscuro.
        /// </summary>
        internal static string RadioButton_DarkTheme {
            get {
                return ResourceManager.GetString("RadioButton_DarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claro.
        /// </summary>
        internal static string RadioButton_LightTheme {
            get {
                return ResourceManager.GetString("RadioButton_LightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oficina.
        /// </summary>
        internal static string RadioButton_Office {
            get {
                return ResourceManager.GetString("RadioButton_Office", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Español.
        /// </summary>
        internal static string RadioButton_Spanish {
            get {
                return ResourceManager.GetString("RadioButton_Spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sistema.
        /// </summary>
        internal static string RadioButton_SystemLanguage {
            get {
                return ResourceManager.GetString("RadioButton_SystemLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sistema.
        /// </summary>
        internal static string RadioButton_SystemTheme {
            get {
                return ResourceManager.GetString("RadioButton_SystemTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Casa (teletrabajo).
        /// </summary>
        internal static string RadioButton_Telework {
            get {
                return ResourceManager.GetString("RadioButton_Telework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar registro.
        /// </summary>
        internal static string RecordDetail_EditTitle {
            get {
                return ResourceManager.GetString("RecordDetail_EditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo registro.
        /// </summary>
        internal static string RecordDetail_NewTitle {
            get {
                return ResourceManager.GetString("RecordDetail_NewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idioma.
        /// </summary>
        internal static string Section_Language {
            get {
                return ResourceManager.GetString("Section_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resumen mensual.
        /// </summary>
        internal static string Section_MonthlySummary {
            get {
                return ResourceManager.GetString("Section_MonthlySummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notificaciones.
        /// </summary>
        internal static string Section_Notifications {
            get {
                return ResourceManager.GetString("Section_Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Franjas horarias.
        /// </summary>
        internal static string Section_TimeSlots {
            get {
                return ResourceManager.GetString("Section_TimeSlots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jornada laboral.
        /// </summary>
        internal static string Section_WorkdaySettings {
            get {
                return ResourceManager.GetString("Section_WorkdaySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sobre la aplicación.
        /// </summary>
        internal static string Settings_Section_About {
            get {
                return ResourceManager.GetString("Settings_Section_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apariencia y comportamiento.
        /// </summary>
        internal static string Settings_Section_AppearanceBehavior {
            get {
                return ResourceManager.GetString("Settings_Section_AppearanceBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuración de usuario.
        /// </summary>
        internal static string Settings_Section_User_Config {
            get {
                return ResourceManager.GetString("Settings_Section_User_Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} entradas.
        /// </summary>
        internal static string Stat_Entries {
            get {
                return ResourceManager.GetString("Stat_Entries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oficina.
        /// </summary>
        internal static string Stat_Office {
            get {
                return ResourceManager.GetString("Stat_Office", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teletrabajo.
        /// </summary>
        internal static string Stat_Telework {
            get {
                return ResourceManager.GetString("Stat_Telework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % Teletrabajo.
        /// </summary>
        internal static string Stat_TeleworkPercentage {
            get {
                return ResourceManager.GetString("Stat_TeleworkPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoy has trabajado {0}.
        /// </summary>
        internal static string Stat_TodayWorked {
            get {
                return ResourceManager.GetString("Stat_TodayWorked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string Stat_Total {
            get {
                return ResourceManager.GetString("Stat_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activa.
        /// </summary>
        internal static string Status_Active {
            get {
                return ResourceManager.GetString("Status_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archivada.
        /// </summary>
        internal static string Status_Archive {
            get {
                return ResourceManager.GetString("Status_Archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactiva.
        /// </summary>
        internal static string Status_Inactive {
            get {
                return ResourceManager.GetString("Status_Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control de tiempo.
        /// </summary>
        internal static string TitleBar_Subtitle {
            get {
                return ResourceManager.GetString("TitleBar_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar.
        /// </summary>
        internal static string Tray_Close {
            get {
                return ResourceManager.GetString("Tray_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abrir.
        /// </summary>
        internal static string Tray_Open {
            get {
                return ResourceManager.GetString("Tray_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to horas.
        /// </summary>
        internal static string Unit_Hours {
            get {
                return ResourceManager.GetString("Unit_Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutos.
        /// </summary>
        internal static string Unit_Minutes {
            get {
                return ResourceManager.GetString("Unit_Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya existe una actividad con este nombre..
        /// </summary>
        internal static string Validation_ActivityNameExists {
            get {
                return ResourceManager.GetString("Validation_ActivityNameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre de la actividad es obligatorio..
        /// </summary>
        internal static string Validation_ActivityNameRequired {
            get {
                return ResourceManager.GetString("Validation_ActivityNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre no puede superar los {0} caracteres..
        /// </summary>
        internal static string Validation_ActivityNameTooLong {
            get {
                return ResourceManager.GetString("Validation_ActivityNameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debes seleccionar una actividad..
        /// </summary>
        internal static string Validation_ActivityRequired {
            get {
                return ResourceManager.GetString("Validation_ActivityRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al guardar la actividad. Inténtalo de nuevo..
        /// </summary>
        internal static string Validation_ActivitySaveError {
            get {
                return ResourceManager.GetString("Validation_ActivitySaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La hora de fin debe ser posterior a la hora de inicio..
        /// </summary>
        internal static string Validation_EndTimeAfterStartTime {
            get {
                return ResourceManager.GetString("Validation_EndTimeAfterStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La hora de fin no es válida..
        /// </summary>
        internal static string Validation_InvalidEndTime {
            get {
                return ResourceManager.GetString("Validation_InvalidEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La hora de inicio no es válida..
        /// </summary>
        internal static string Validation_InvalidStartTime {
            get {
                return ResourceManager.GetString("Validation_InvalidStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El registro se solapa con otro registro existente ({0} - {1})..
        /// </summary>
        internal static string Validation_OverlappingRecord {
            get {
                return ResourceManager.GetString("Validation_OverlappingRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La franja se solapa con otra franja existente ({0} - {1})..
        /// </summary>
        internal static string Validation_OverlappingSlot {
            get {
                return ResourceManager.GetString("Validation_OverlappingSlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al guardar el registro. Inténtalo de nuevo..
        /// </summary>
        internal static string Validation_RecordSaveError {
            get {
                return ResourceManager.GetString("Validation_RecordSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET 10, WPF, SQLite.
        /// </summary>
        internal static string Value_Technology {
            get {
                return ResourceManager.GetString("Value_Technology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurar día.
        /// </summary>
        internal static string Button_ConfigureDay {
            get {
                return ResourceManager.GetString("Button_ConfigureDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurar día.
        /// </summary>
        internal static string Dialog_ConfigureDay_Title {
            get {
                return ResourceManager.GetString("Dialog_ConfigureDay_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de día.
        /// </summary>
        internal static string Label_DayType {
            get {
                return ResourceManager.GetString("Label_DayType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duración objetivo de la jornada.
        /// </summary>
        internal static string Label_TargetDuration {
            get {
                return ResourceManager.GetString("Label_TargetDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laborable (normal).
        /// </summary>
        internal static string DayType_WorkDay {
            get {
                return ResourceManager.GetString("DayType_WorkDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laborable (intensiva).
        /// </summary>
        internal static string DayType_IntensiveDay {
            get {
                return ResourceManager.GetString("DayType_IntensiveDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Festivo.
        /// </summary>
        internal static string DayType_Holiday {
            get {
                return ResourceManager.GetString("DayType_Holiday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Libre elección.
        /// </summary>
        internal static string DayType_FreeChoice {
            get {
                return ResourceManager.GetString("DayType_FreeChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vacaciones.
        /// </summary>
        internal static string DayType_Vacation {
            get {
                return ResourceManager.GetString("DayType_Vacation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restablecer valores por defecto.
        /// </summary>
        internal static string Button_ResetToDefaults {
            get {
                return ResourceManager.GetString("Button_ResetToDefaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No aplica.
        /// </summary>
        internal static string Label_NotApplicable {
            get {
                return ResourceManager.GetString("Label_NotApplicable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La duración no es válida. Use el formato HH:mm (ejemplo: 08:00).
        /// </summary>
        internal static string Validation_InvalidDuration {
            get {
                return ResourceManager.GetString("Validation_InvalidDuration", resourceCulture);
            }
        }
    }
}
